version: '3.8'

volumes:
  pgdata:
  cache-data:

services:
  postgres_test_task:
    container_name: postgres_test_task
    image: postgres:14.7
    restart: on-failure
    env_file:
      - '.env'
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis_test_task:
    image: redis:6
    container_name: redis_test_task
    restart: on-failure
    env_file:
      - '.env'
    volumes:
      - cache-data:/data
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    expose:
      - '${REDIS_PORT}'
    command: '--port ${REDIS_PORT}'
  app:
    container_name: app
    restart: on-failure
    build:
      context: .
      dockerfile: docker/${NODE_ENV}/.Dockerfile
    env_file:
      - '.env'
    volumes:
      - /base/node_modules/
      - ./:/base
    ports:
      - '${APP_PORT}:${APP_PORT}'
    depends_on:
      - postgres_test_task
      - redis_test_task
